### ISSUE TITLE
Changing a mine to silent in game does not work.

### ISSUE THREAD

**Issue by glostone** [JoseGamerPT/RealMines#16]
When using the command "/realmines silent <minename>" the mine is not set to silent. 
Changing the value in the "mines.yml" file works fine.
[config.yml.txt](https://github.com/JoseGamerPT/RealMines/files/9996106/config.yml.txt)
[mines.yml.txt](https://github.com/JoseGamerPT/RealMines/files/9996107/mines.yml.txt)

**Comment by neziw** [comment]
I have few ideas what's wrong in the code. Thanks for report, I will look into as fast as I can.

**Comment by neziw** [comment]
Issue fixed in latest dev build (see https://github.com/JoseGamerPT/RealMines/actions/runs/3456239695). Thanks!
